# include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  strong-mode:
    # To disallow both implicit downcasts and implicit dynamic types in the analysis options file:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    todo: ignore
    unused_local_variable: info
    invalid_assignment: error
    missing_return: error
    dead_code: info
    todo: ignore

  exclude:
    - flutter/**
    # - lib/api/*.dart
    - lib/api/json_models/*.g.dart
    - src/test/_data/**

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - annotate_overrides
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_returning_null
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - always_declare_return_types
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
