name: f_date
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  # sdk: '>=2.11.0 <3.0.0'
  # sdk: ">=2.12.0-0 <3.0.0"
  # flutter: ">=1.12.13+hotfix.5 <2.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # rxdart: ^0.25.0
  path_provider: ^1.6.27
  pedantic: ^1.9.2
  image_picker: ^0.6.7+22
  sqflite: ^1.3.0
  postgres: ^2.2.0
  path: ^1.7.0

  # Authentication
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"
  firebase_dynamic_links: ^0.7.0+1

  # google_sign_in: ^4.5.1
  # flutter_facebook_auth: ^1.0.0
  # sign_in_with_apple: ^2.5.2
  # crypto: ^2.1.5

  http: ^0.12.0

  # flutter_secure_storage: ^3.3.5



  json_annotation: ^3.0.0
  # firebase_core: ^0.3.4

  # Add the dependency for the Firebase Core Flutter SDK
  # firebase_core: ^0.4.0+9
  # Add the dependency for the FlutterFire plugin for Google Analytics
  # firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  # firebase_auth: ^0.14.0+5
  # cloud_firestore: ^0.12.9+5
  built_value: ^7.1.0
  built_value_generator: ^7.1.0
  # cloud_firestore: ^0.9.1
  # shared:
    # path: ./shared


dev_dependencies:
  flutter_test:
    sdk: flutter
  # built_value_generator: "^6.1.6"
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  flutter_driver:
    sdk: flutter
  # mockito: 4.0.0
  # test: any

flutter:
  uses-material-design: true
  fonts:
    - family: Hack
      fonts:
        - asset: assets/fonts/Hack/Hack-Italic.ttf
        - asset: assets/fonts/Hack/Hack-Regular.ttf
# The style property specifies whether the outlines in the file are italic or normal. These values correspond to the FontStyle and can be used in the fontStyle property of a TextStyle object.
          style: italic
    - family: Lato
      fonts:
      - asset: assets/fonts/Lato/Lato-Regular.ttf
      - asset: assets/fonts/Lato/Lato-Bold.ttf
# The weight property specifies the weight of the outlines in the file as an integer multiple of 100, between 100 and 900. These values correspond to the FontWeight and can be used in the fontWeight property of a TextStyle object.
        weight: 700
